version: '3.8'
services:
  backend:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV
      - PORT
      - DATABASE_URL
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: