version: '3.8'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpass
      POSTGRES_DB: notedb
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: