version: '3.9'
services:
  db-dev:
    image: postgres:15
    container_name: db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5433:5432' # dev ใช้ port 5433
