version: '3.8'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: notes_db
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: