-- AlterTable
ALTER TABLE "Note" ADD COLUMN     "user_id" INTEGER NOT NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Note" ADD CONSTRAINT "Note_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
